<?php

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
//    public function findContactWhereNumberIs($contact) {
//        $contact_info = $this->getEntityManager()->createQuery('
//        SELECT a FROM AppBundle:Contact a
//        WEHRE a.contact like :contact')->setParameter('contact', '%'.$contact.'%');
//
//        return $contact_info;
//    }
}
